Repository telekom-mms/docker-management-container, pull requests merged in 2023-01, with the labels that each got.

#57 Enhancement Repository Configuration and Optimize Render Script
  .github/workflows/linting.yml
  Dockerfile.template
  README.MD
  examples/full_build.yaml
  render.sh
Labels: bug, documentation, enhancement, major, breaking

#61 [FIX] Fixed order of templates to add repositories before installing …
  template.d/11_repositories
  template.d/12_packages
Labels: bug, patch

#62 Add Tests and remove error ignores
  .github/workflows/build.yml
  template.d/00_image
  template.d/10_tools
  template.d/11_repositories
  template.d/12_packages
  template.d/13_binaries
  template.d/20_tools_config
  template.d/21_requirements
  template.d/22_extensions
  template.d/30_post_build_config
  template.d/31_profiles
  template.d/32_post_build_commands
Labels: enhancement
