Repository telekom-mms/docker-management-container, pull requests merged in 2023-03, with the labels that each got.

#74 add update package manager database before package install
  template.d/12_packages
Labels: bug

#77 Pip requirements
  README.MD
  examples/full_build.yaml
  render.sh
  template.d/21_requirements
Labels: enhancement, minor

#79 rm table style
  README.MD
Labels: documentation, patch

#81 Renovate preset
  README.MD
  default.json
Labels: enhancement, minor
